// Generated by CoffeeScript 1.8.0
(function() {
  var VideoStream, runStaticHTMLServer, videoStream, videoStream2;

  VideoStream = require('node-rstp-stream');

  videoStream = new VideoStream({
    name: 'wowza',
    streamUrl: 'rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov',
    wsPort: 9999,
    width: 240,
    height: 160
  });

  videoStream2 = new VideoStream({
    name: 'wowza2',
    streamUrl: 'rtsp://quicktime.uvm.edu:1554/waw/wdi05hs2b.mov',
    wsPort: 9998,
    width: 352,
    height: 288
  });

  runStaticHTMLServer = function() {
    var file, static_;
    static_ = require('node-static');
    file = new static_.Server("./public");
    require("http").createServer(function(request, response) {
      request.addListener("end", function() {
        file.serve(request, response);
      }).resume();
    }).listen(80);
    return console.log("HTTP server listening on port 80");
  };

  runStaticHTMLServer();

}).call(this);
