// Generated by CoffeeScript 1.8.0
(function() {
  var VideoStream, config, runStaticHTMLServer;

  VideoStream = require('node-rstp-stream');

  config = require('../config');

  config.streams.forEach(function(streamConfig) {
    var videoStream;
    return videoStream = new VideoStream(streamConfig);
  });

  runStaticHTMLServer = function() {
    var file, static_;
    static_ = require('node-static');
    file = new static_.Server("./public");
    require("http").createServer(function(request, response) {
      request.addListener("end", function() {
        file.serve(request, response);
      }).resume();
    }).listen(80);
    return console.log("HTTP server listening on port 80");
  };

  runStaticHTMLServer();

}).call(this);
